slides.push(slide('Produto-Âncora', `${header('07 · PRODUTO-ÂNCORA', 'Kit organizador modular', 'Melhor equilíbrio simulado entre apelo visual, possibilidade de kit, logística e contribuição unitária.')}
    <div class="grid-2 align-center"><div class="card highlight reveal"><p class="eyebrow">SIMULAÇÃO UNITÁRIA</p><div class="anchor-price">${C.money(anchor.price)}</div><div class="metric-grid">${metric('Compra', C.money(anchor.cost))}${metric('Taxa + tributo', C.money(anchor.fee + anchor.tax))}${metric('Logística', C.money(anchor.shipping + anchor.packaging))}${metric('Publicidade', C.money(anchor.marketing))}${metric('Lucro líquido un.', C.money(anchor.profit), anchor.profit >= 0 ? 'positive' : 'negative')}${metric('Margem / ROI', `${C.pct(anchor.margin)} / ${C.pct(anchor.roi)}`)}</div></div>
    <div class="card reveal"><h3>Capacidade teórica do capital</h3><div class="big-number">${Math.floor(d.finance.initialInvestment / anchor.cost)}</div><p class="muted">unidades se 100% do capital fosse estoque — cenário não recomendado.</p><ul class="list"><li><span>Lote na alocação proposta</span><b>${Math.floor(d.allocation[0].value * .30 / anchor.cost)} un.</b></li><li><span>Capital no SKU</span><b>${C.money(Math.floor(d.allocation[0].value * .30 / anchor.cost) * anchor.cost)}</b></li><li><span>Risco logístico</span><b>baixo / médio</b></li></ul></div></div>
    ${source(`${tag('assumption')} Produto e unit economics ilustrativos; validar amostra, procura, fornecedor e tarifa por anúncio antes da compra.`)}`));

  slides.push(slide(`Distribuição dos ${C.money(d.finance.initialInvestment).replace(',00', '')}`, `${header('08 · CAPITAL', 'Cada real deve financiar validação ou resiliência.', `A distribuição fecha exatamente em ${C.money(C.allocationTotal())}.`)}
    <div class="grid-2 align-center"><div class="card chart reveal" id="allocationChart"></div><div class="allocation-list reveal">${d.allocation.map(a => `<div class="allocation-row"><span><i class="legend-dot" style="background:${a.color}"></i>${a.name}<small>${a.objective}</small></span><div class="bar-track"><div class="bar-fill" style="width:${a.value / d.finance.initialInvestment * 100}%;background:${a.color}"></div></div><b>${C.money(a.value)}<small>${C.pct(a.value / d.finance.initialInvestment)}</small></b></div>`).join('')}</div></div>
    ${source(`${tag('assumption')} Proposta inicial; reequilibrar após cotações e regras de repasse dos canais.`)}`));

  const inventory = C.inventoryRows(d.finance.initialInvestment);
  slides.push(slide('Estratégia de Estoque', `${header('09 · ESTOQUE', 'Cinco SKUs para encontrar o sinal.', 'A diversificação 30 / 25 / 20 / 15 / 10 limita concentração e compara giro, margem e conversão.')}
    <div class="table-wrap reveal"><table><thead><tr><th>Produto</th><th>Mix</th><th>Estoque</th><th>Unidades</th><th>Preço</th><th>Margem</th><th>Venda mensal</th><th>Lucro estimado</th><th>Status</th></tr></thead><tbody>${inventory.map(x => `<tr><td><b>${x.product}</b></td><td>${C.pct(x.share)}</td><td>${C.money(x.stockValue)}</td><td>${x.units}</td><td>${C.money(x.price)}</td><td>${C.pct(x.margin)}</td><td>${x.monthlyUnits} un.</td><td>${C.money(x.estimatedProfit)}</td><td><span class="status status-${x.index < 1 ? 'green' : x.index < 3 ? 'yellow' : 'neutral'}">${x.status}</span></td></tr>`).join('')}</tbody></table></div>
    <div class="grid-3 reveal"><div class="card"><h3>Reposição</h3><p>Repor apenas quando o sell-through confirmar velocidade.</p></div><div class="card"><h3>Corte</h3><p>Reduzir SKU sem tração após duas rodadas de otimização.</p></div><div class="card"><h3>Caixa</h3><p>Não consumir reserva para sustentar estoque parado.</p></div></div>
    ${source(`${tag('projection')} Quantidades e vendas mensais derivadas das premissas de custo, mix e demanda em js/data.js.`)}`));
  const sale100 = { price: 100, cost: 35.6, fee: 18, tax: 6, shipping: 11, packaging: 2.5, marketing: 11, contribution: 15.9 };
  slides.push(slide('Unit Economics', `${header('10 · ECONOMIA UNITÁRIA', 'R$ 100 de receita não são R$ 100 de caixa.', 'A contribuição precisa pagar custos fixos, perdas e ainda remunerar o capital.')}
    <div class="grid-2 align-center"><div class="card chart reveal" id="waterfallChart"></div><div class="card reveal"><p class="eyebrow">VENDA SIMULADA</p><div class="unit-stack">${[['Receita bruta', 100, 'positive'], ['Produto', -35.6, 'negative'], ['Marketplace', -18, 'negative'], ['Logística + embalagem', -13.5, 'negative'], ['Publicidade', -11, 'negative'], ['Impostos', -6, 'negative'], ['Margem de contribuição', 15.9, 'gold']].map(([l, v, c]) => `<div><span>${l}</span><b class="${c}">${v > 0 && l !== 'Receita bruta' ? '+' : ''}${C.money(v)}</b></div>`).join('')}</div><div class="formula">receita − produto − canal − logística − mídia − impostos = contribuição</div></div></div>
    ${source(`${tag('assumption')} Exemplo normalizado em R$ 100; custos operacionais fixos são descontados nos cenários financeiros.`)}`));

  slides.push(slide('Métricas-Chave', `${header('11 · SISTEMA DE GESTÃO', 'Medir valor, eficiência e velocidade.', 'Nenhuma métrica isolada autoriza escala.')}
    <div class="grid-4 formula-grid reveal">${[
      ['CAC', 'mídia ÷ novos clientes', 'custo para adquirir'], ['ROI', d.formulas.roi, 'retorno do capital'], ['ROAS', d.formulas.roas, 'eficiência da mídia'], ['Margem líquida', d.formulas.margin, 'qualidade da receita'], ['Ticket médio', 'receita ÷ pedidos', 'valor por pedido'], ['Conversão', d.formulas.conversion, 'eficiência da página'], ['Giro de estoque', d.formulas.turnover, 'velocidade do capital'], ['Payback', d.formulas.payback, 'tempo de recuperação']
    ].map(([name, formula, meaning]) => `<div class="card"><h3>${name}</h3><div class="formula">${formula}</div><p class="muted">${meaning}</p></div>`).join('')}</div>
    ${source(`${tag('assumption')} Fórmulas gerenciais. Definir janela e atribuição consistentes antes de comparar períodos.`)}`));

  slides.push(slide('Cenários Financeiros', `${header('12 · CENÁRIOS', 'Resultado depende das premissas — inclusive para baixo.', 'Conservador, base e otimista usam pedidos, ticket, custo, taxa, logística, mídia e operação explícitos.')}
    <div class="scenario-grid reveal">${scenarios.map(s => `<article class="scenario-card" style="--scenario:${s.color}"><p>${s.name}</p><strong>${C.money(s.profit)}</strong><small>lucro mensal</small><dl><div><dt>Pedidos</dt><dd>${s.orders}</dd></div><div><dt>Faturamento</dt><dd>${C.money(s.revenue)}</dd></div><div><dt>Margem</dt><dd>${C.pct(s.margin)}</dd></div><div><dt>ROI / ciclo</dt><dd>${C.pct(s.roi)}</dd></div><div><dt>Payback</dt><dd>${s.payback ? `${s.payback.toFixed(1)} ciclos` : 'não recupera'}</dd></div><div><dt>Reinvestido</dt><dd>${C.money(s.reinvested)}</dd></div></dl></article>`).join('')}</div>
    <div class="card chart scenario-chart reveal" id="scenarioChart"></div>
    ${source(`${tag('projection')} Projeções mensais, sem garantia. Premissas completas em js/data.js; ROI = lucro mensal ÷ ${C.money(d.finance.initialInvestment)}.`)}`));
  const marketingTotal = C.marketingTotal();
  slides.push(slide('Estratégia de Marketing', `${header('13 · AQUISIÇÃO', 'Começar perto da conversão.', 'Marketplace Ads recebe 60% do orçamento por permitir mensuração mais próxima da venda.')}
    <div class="grid-2"><div class="card reveal"><div class="marketing-stack">${d.marketing.map(m => `<article><div><strong>${m.channel}</strong><small>${m.goal}</small></div><b>${C.money(m.value)}<small>${C.pct(m.value / marketingTotal)}</small></b><div class="bar-track"><div class="bar-fill" style="width:${m.value / marketingTotal * 100}%"></div></div><em>${m.metric}</em></article>`).join('')}</div></div>
    <div class="card reveal"><h3>Regra de aumento</h3><div class="decision-rule"><span>1</span><p>Margem unitária permanece positiva após mídia.</p><span>2</span><p>ROAS supera o ponto de equilíbrio do produto.</p><span>3</span><p>Estoque e caixa suportam o novo ritmo.</p></div><div class="callout"><b>Sem os três sinais:</b> otimizar anúncio, preço ou oferta — não ampliar orçamento.</div></div></div>
    ${source(`${tag('assumption')} Orçamento total de ${C.money(marketingTotal)}. Atribuição e ROAS devem ser avaliados por SKU e coorte.`)}`));

  slides.push(slide('Regra de Reinvestimento', `${header('14 · CAPITAL COMPOSTO', 'Lucro não é retirada no ciclo de validação.', 'Reinvestir resultado positivo; preservar caixa e cortar exposição quando o resultado for negativo.')}
    <div class="reinvest-flow reveal"><div class="reinvest-source"><small>LUCRO DO CICLO</small><strong>100%</strong></div><i>→</i>${[['70%', 'Estoque / crescimento', 'blue'], ['20%', 'Marketing', 'purple'], ['10%', 'Caixa / reserva', 'green']].map(([v, l, c]) => `<div class="reinvest-node ${c}"><strong>${v}</strong><span>${l}</span></div>`).join('')}</div>
    <div class="grid-2 reveal"><div class="card highlight"><h3>Resultado positivo</h3><p>Repor vencedores, financiar mídia sustentável e ampliar reserva.</p></div><div class="card danger-card"><h3>Resultado negativo</h3><p><b>0% para escala.</b> Pausar mídia ineficiente, liquidar lentamente o parado, revisar preço e preservar a reserva.</p></div></div>
    ${source(`${tag('assumption')} Regra padrão 70 / 20 / 10; adaptar à cobertura de estoque e à necessidade de caixa.`)}`));

  slides.push(slide('Plano de 90 Dias', `${header('15 · EXECUÇÃO', 'Quatro fases. Um gate por avanço.', 'O calendário protege o capital contra decisões baseadas em poucas vendas ou vaidade.')}
    <div class="timeline reveal">${d.roadmap.map((r, i) => `<article class="card"><span class="phase-number">${i + 1}</span><p class="eyebrow">DIAS ${r.days}</p><h3>${r.title}</h3><p>${r.actions}</p><div class="gate"><small>GATE</small><b>${r.gate}</b></div></article>`).join('')}</div>
    <div class="callout reveal">Ritual semanal: caixa → margem → mídia → giro → reputação → próxima ação.</div>
    ${source(`${tag('assumption')} Plano operacional recomendado; prazos dependem de fornecedor, cadastro e logística.`)}`));

  const k = { orders: scenarios[1].orders, revenue: scenarios[1].revenue, profit: scenarios[1].profit, margin: scenarios[1].margin, roi: scenarios[1].roi, roas: scenarios[1].roas, conversion: d.kpis.conversion, averageTicket: scenarios[1].ticket, stockCoverage: d.kpis.stockCoverage };
  slides.push(slide('Dashboard de KPIs', `${header('16 · PAINEL DE CONTROLE', 'A operação cabe em nove sinais.', 'Valores simulados e editáveis em js/data.js. Atualize com dados reais assim que a venda começar.')}
    <div class="dashboard reveal">${metric('Pedidos', k.orders)}${metric('Receita', C.money(k.revenue))}${metric('Lucro líquido', C.money(k.profit), 'positive')}${metric('Margem', C.pct(k.margin))}${metric('ROI', C.pct(k.roi))}${metric('ROAS', `${k.roas.toFixed(1)}×`)}${metric('Conversão', C.pct(k.conversion))}${metric('Ticket médio', C.money(k.averageTicket))}${metric('Cobertura de estoque', `${k.stockCoverage} dias`)}</div>
    <div class="grid-3 reveal"><div class="kpi-band"><span>Margem mínima</span><b>≥ 10%</b><i style="width:72%"></i></div><div class="kpi-band"><span>Giro alvo</span><b>≤ 60 dias</b><i style="width:65%"></i></div><div class="kpi-band"><span>Estoque parado</span><b>&lt; 15%</b><i style="width:38%"></i></div></div>
    ${source(`${tag('projection')} Snapshot demonstrativo; não representa resultado realizado.`)}`));
 
